version: "3"

services:
  cassandra-seed-1:
    container_name: "cassandra-seed-1"
    image: cassandra:latest
    ports:
      - 9042:9042
    networks:
      - dc1
      - con
    environment:
      - "CASSANDRA_CLUSTER_NAME=cluster1"
      - "CASSANDRA_SEEDS=172.21.0.2,172.21.0.3"
      - "CASSANDRA_DC=dc1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_LISTEN_ADDRESS=172.21.0.2"



  cassandra-seed-2:
    container_name: "cassandra-seed-2"
    image: cassandra:latest
    ports:
      - 9043:9042
    networks:
      - dc2
      - con
    environment:
      - "CASSANDRA_CLUSTER_NAME=cluster1"
      - "CASSANDRA_SEEDS=172.21.0.2,172.21.0.3"
      - "CASSANDRA_DC=dc2"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_LISTEN_ADDRESS=172.21.0.3"

  cassandra-1-1:
      container_name: "cassandra-1-1"
      image: cassandra:latest
      environment:
        - "CASSANDRA_CLUSTER_NAME=cluster1"
        - "CASSANDRA_SEEDS=cassandra-seed-1"
        - "CASSANDRA_DC=dc1"
        - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      networks:
        - dc1
        - con


  rest-1:
    container_name: "rest-1"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - REPLICATION_FACTOR=1
    networks:
      - dc1

  cassandra-1-2:
    container_name: "cassandra-1-2"
    image: cassandra:latest
    environment:
      - "CASSANDRA_CLUSTER_NAME=cluster1"
      - "CASSANDRA_SEEDS=cassandra-seed-2"
      - "CASSANDRA_DC=dc2"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      - dc2
      - con

  rest-2:
    container_name: "rest-2"
    build:
      context: .
      dockerfile: ./DockerFile2
    ports:
      - 8081:8080
    environment:
      - REPLICATION_FACTOR=1
    networks:
      - dc2

networks:
  dc1:
    driver: bridge
  dc2:
    driver: bridge
  con:
    driver: bridge