version: "3"
services:
  cassandra-1:
    image: "cassandra:3"
    expose: ["7199", "7001", "9042", "9160"]
    environment:
      - CASSANDRA_CLUSTER_NAME=KAJ
      - CASSANDRA_SEEDS=cassandra-1
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
  cassandra-2:
    depends_on:
      - "cassandra-1"
    image: "cassandra:3"
    expose: ["7199", "7001", "9042", "9160"]
    environment:
      - CASSANDRA_CLUSTER_NAME=KAJ
      - CASSANDRA_SEEDS=cassandra-1
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'
  cassandra-3:
    depends_on:
      - "cassandra-2"
    image: "cassandra:3"
    expose: ["7199", "7001", "9042", "9160"]
    environment:
      - CASSANDRA_CLUSTER_NAME=KAJ
      - CASSANDRA_SEEDS=cassandra-1
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f'
  app:
    build:
      context: .
    ports:
      - "8000:8080"
    depends_on:
      - "cassandra-3"